Angela Diaz | 
ANA675 Neural Networks & Deep Learning |
Week 2 Assignment 2 |
7/21/2024

## Use Keras to design and train an MLP neural network (Backpropagation algorithm)

In [1]:
# Import Packages
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [2]:
# Create the table
#  x  y  z  f
#  0  0  0  0
#  0  0  1  1
#  0  1  0  1
#  0  1  1  0
#  1  0  0  1
#  1  0  1  0
#  1  1  0  0
#  1  1  1  1

In [3]:
# Create the input data and their corresponding output.
X = ([0,0,0], [0,0,1], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,0], [1,1,1])
y = ([0], [1], [1], [0], [1], [0], [0], [1])

In [4]:
# Convert to tensors
X = tf.convert_to_tensor(X, dtype=tf.float32)
y = tf.convert_to_tensor(y, dtype=tf.float32)

In [5]:
X.shape

TensorShape([8, 3])

In [6]:
y.shape

TensorShape([8, 1])

In [7]:
#Design the neural network. 
model = keras.models.Sequential([
    keras.layers.Dense(5, input_dim = 3, activation = "relu"),
    keras.layers.Dense(1, activation = "softmax")
])

In [8]:
# Compile the model
model.compile(optimizer = Adam(learning_rate = 0.01),
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 20        
                                                                 
 dense_1 (Dense)             (None, 1)                 6         
                                                                 
Total params: 26 (104.00 Byte)
Trainable params: 26 (104.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
# Train the model
model.fit(X, y, epochs = 10)

Epoch 1/10
1/1 [==============================] - 1s 572ms/step - loss: 0.6771 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6750 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6734 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6715 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6695 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6681 - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6668 - accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6655 - accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6640 - accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6625 - accuracy: 0.5000


In [11]:
# Evaluate the model
loss, accuracy = model.evaluate(X,y)
print(f'Loss: {loss}, Accuracy: {accuracy}')

1/1 [==============================] - 0s 147ms/step - loss: 0.6611 - accuracy: 0.5000
Loss: 0.6610808372497559, Accuracy: 0.5


In [12]:
# Make predictions
prediction = model.predict(X)
print(prediction)

1/1 [==============================] - 0s 103ms/step
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [13]:
# Tune Model by adding hidden layer
model2 = keras.models.Sequential([
    keras.layers.Dense(5, input_dim = 3, activation = "relu"),
    keras.layers.Dense(3, activation = "relu"),
    keras.layers.Dense(1, activation = "softmax")
])

In [14]:
model2.compile(optimizer = Adam(learning_rate = 0.01),
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])

In [15]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 5)                 20        
                                                                 
 dense_3 (Dense)             (None, 3)                 18        
                                                                 
 dense_4 (Dense)             (None, 1)                 4         
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model2.fit(X, y, epochs = 10)

Epoch 1/10
1/1 [==============================] - 1s 515ms/step - loss: 0.7296 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 14ms/step - loss: 0.7218 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 0.7148 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 0.7087 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 0.7033 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6984 - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6946 - accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6917 - accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6881 - accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6838 - accuracy: 0.5000


In [17]:
loss, accuracy = model2.evaluate(X,y)
print(f'Loss: {loss}, Accuracy: {accuracy}')

1/1 [==============================] - 0s 114ms/step - loss: 0.6811 - accuracy: 0.5000
Loss: 0.6810842156410217, Accuracy: 0.5


In [18]:
prediction = model2.predict(X)
print(prediction)

1/1 [==============================] - 0s 54ms/step
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [20]:
# Tune Model by increasing neurons in hidden layer
model3 = keras.models.Sequential([
    keras.layers.Dense(15, input_dim = 3, activation = "relu"),
    keras.layers.Dense(13, activation = "relu"),
    keras.layers.Dense(1, activation = "softmax")
])

In [21]:
model3.compile(optimizer = Adam(learning_rate = 0.01),
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])

In [22]:
model3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 15)                60        
                                                                 
 dense_6 (Dense)             (None, 13)                208       
                                                                 
 dense_7 (Dense)             (None, 1)                 14        
                                                                 
Total params: 282 (1.10 KB)
Trainable params: 282 (1.10 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model3.fit(X, y, epochs = 10)

Epoch 1/10
1/1 [==============================] - 1s 541ms/step - loss: 0.7006 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6908 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6835 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6812 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6779 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6732 - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6692 - accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6662 - accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6631 - accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6598 - accuracy: 0.5000


In [24]:
loss, accuracy = model3.evaluate(X,y)
print(f'Loss: {loss}, Accuracy: {accuracy}')

1/1 [==============================] - 0s 99ms/step - loss: 0.6560 - accuracy: 0.5000
Loss: 0.6559765338897705, Accuracy: 0.5


In [25]:
prediction = model3.predict(X)
print(prediction)

1/1 [==============================] - 0s 49ms/step
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
